### ISSUE TITLE
Variable Naming Conventions

### ISSUE THREAD

**Issue by tylersloan** [BoomTownROI/css#1]
We may be able to base this off what is in place in Boomstrap already. It's worth a discussion though so all variable names are coherent and not so specific that editing down the road is difficult.

**Comment by ryanshrum** [comment]
It follows a similar naming convention. The only thing I've never seen before is

> It is acceptable to prefix variable names that are intended to be used only within the same file with an underscore (e.g. $_my-variable). 

But I tend to like that, but typically error on putting on vars in one vars file vs naming them in a file (potentially for mixins, but that's about it).

**Comment by tylersloan** [comment]
I can imagine when it's useful to name a variable a value to use inside a block if you're going to do some calculations on it or something. I'm good with the underscore in front of it when it's defined in the file it's used in. It's a scoped variable. They are also useful in writing BEM and inside @for or @each loops in Sass.

If you don't have any other thoughts on how to name a variable well, maybe let's hold off on writing a rule about it until we hit this wall. I imagine we won't be writing many new variables too soon, anyway.
